// Browser port of the seafloor model in enceladus_MIF/seafloor/seafloor.py.
//
// Loads the pre-generated terrain from assets/seafloor/ (regenerated by hand
// with seafloor.py and re-copied there) and answers the same queries the
// Python model does: floor depth, and whether a point is inside a hydrothermal
// chimney. Nothing here is shown to participants.
//
// Coordinates: the website uses x,y in -5000..+5000 m, centred on the base
// station. The seafloor model uses 0..10000 m with its origin at a corner, so
// every query is shifted by DOMAIN_OFFSET_M before it touches the data.
// z is depth below the ice-ocean interface, positive downward.

import { MISSION_CONFIG } from "./config.js";

const DATA_BASE = new URL("../../../assets/seafloor/", import.meta.url);
const DOMAIN_M = 10000;
const DOMAIN_OFFSET_M = 5000;
const FINE_FIELD_COUNT = 7;

let loading = null;
let model = null;

// ===================== .npy parsing =====================

// Parses a version 1.x/2.x .npy file holding a C-ordered little-endian float32 2D array.
function parseNpy(buffer) {
  const bytes = new Uint8Array(buffer);
  const magic = String.fromCharCode(...bytes.subarray(0, 6));
  if (magic !== "\x93NUMPY") throw new Error("Not an .npy file");

  const major = bytes[6];
  let headerLen;
  let headerStart;
  if (major === 1) {
    headerLen = bytes[8] | (bytes[9] << 8);
    headerStart = 10;
  } else {
    headerLen = (bytes[8] | (bytes[9] << 8) | (bytes[10] << 16) | (bytes[11] << 24)) >>> 0;
    headerStart = 12;
  }

  const header = new TextDecoder("latin1").decode(bytes.subarray(headerStart, headerStart + headerLen));
  if (!/'descr':\s*'<f4'/.test(header)) throw new Error("Expected little-endian float32 .npy");
  if (/'fortran_order':\s*True/.test(header)) throw new Error("Fortran-ordered .npy not supported");

  const shape = header.match(/'shape':\s*\((\d+),\s*(\d+)\)/);
  if (!shape) throw new Error("Expected a 2D .npy array");
  const rows = Number(shape[1]);
  const cols = Number(shape[2]);

  const dataStart = headerStart + headerLen;
  const data = new Float32Array(buffer.slice(dataStart, dataStart + rows * cols * 4));
  return { rows, cols, data };
}

// ===================== Vent catalogue (CSV) =====================

function parseVentCatalogue(text) {
  const lines = text.trim().split(/\r?\n/);
  const header = lines[0].split(",");
  const col = (name) => header.indexOf(name);
  const idx = {
    vent_id: col("vent_id"), field_id: col("field_id"), field_type: col("field_type"),
    x_m: col("x_m"), y_m: col("y_m"), vent_height_m: col("vent_height_m"),
    field_center_x_m: col("field_center_x_m"), field_center_y_m: col("field_center_y_m"),
    active_field_radius_m: col("active_field_radius_m")
  };

  const vents = [];
  const fields = new Map();
  for (const line of lines.slice(1)) {
    const c = line.split(",");
    vents.push({
      ventId: Number(c[idx.vent_id]),
      fieldId: Number(c[idx.field_id]),
      fieldType: c[idx.field_type],
      x: Number(c[idx.x_m]),          // seafloor coordinates
      y: Number(c[idx.y_m]),
      heightM: Number(c[idx.vent_height_m])
    });
    const fieldId = Number(c[idx.field_id]);
    if (!fields.has(fieldId)) {
      fields.set(fieldId, {
        fieldId,
        cx: Number(c[idx.field_center_x_m]),
        cy: Number(c[idx.field_center_y_m]),
        r: Number(c[idx.active_field_radius_m])
      });
    }
  }
  return { vents, fields: [...fields.values()] };
}

// ===================== Loading =====================

/** Loads the seafloor data once; later calls return the same promise. */
export function loadSeafloor() {
  if (!loading) {
    loading = (async () => {
      const [coarseBuf, csvText, ...fineBufs] = await Promise.all([
        fetch(new URL("seafloor_coarse.npy", DATA_BASE)).then((r) => r.arrayBuffer()),
        fetch(new URL("CRADLE_7Field_Nonuniform_Canonical_v5.csv", DATA_BASE)).then((r) => r.text()),
        ...Array.from({ length: FINE_FIELD_COUNT }, (_, i) =>
          fetch(new URL(`seafloor_fine_field${i + 1}.npy`, DATA_BASE)).then((r) => r.arrayBuffer())
        )
      ]);

      const coarse = parseNpy(coarseBuf);
      const catalogue = parseVentCatalogue(csvText);

      // Fine patches: one per field, covering the square around the active circle,
      // clipped to the domain — same bounds seafloor.py used to build them.
      const patches = catalogue.fields.map((f) => {
        // seafloor_fine_field{N}.npy belongs to field N.
        const npy = parseNpy(fineBufs[f.fieldId - 1]);
        const x0 = Math.max(0, f.cx - f.r);
        const x1 = Math.min(DOMAIN_M, f.cx + f.r);
        const y0 = Math.max(0, f.cy - f.r);
        const y1 = Math.min(DOMAIN_M, f.cy + f.r);
        return { ...f, nx: npy.rows, ny: npy.cols, x0, x1, y0, y1, data: npy.data };
      });

      model = {
        coarse: { nx: coarse.rows, ny: coarse.cols, data: coarse.data },
        patches,
        vents: catalogue.vents
      };
      return model;
    })();
  }
  return loading;
}

// ===================== Queries (seafloor coordinates internally) =====================

// Bilinear lookup on a regular grid that spans [x0,x1] x [y0,y1] with nx x ny points.
function bilinear(grid, nx, ny, x0, x1, y0, y1, x, y) {
  const fx = Math.min(Math.max(((x - x0) / (x1 - x0)) * (nx - 1), 0), nx - 1);
  const fy = Math.min(Math.max(((y - y0) / (y1 - y0)) * (ny - 1), 0), ny - 1);
  const i0 = Math.floor(fx), j0 = Math.floor(fy);
  const i1 = Math.min(i0 + 1, nx - 1), j1 = Math.min(j0 + 1, ny - 1);
  const tx = fx - i0, ty = fy - j0;

  const at = (i, j) => grid[i * ny + j];
  return (1 - tx) * (1 - ty) * at(i0, j0) + tx * (1 - ty) * at(i1, j0)
       + (1 - tx) * ty * at(i0, j1) + tx * ty * at(i1, j1);
}

// Upward relief above the base depth at seafloor coords (sx, sy).
function elevationS(sx, sy) {
  let best = null;
  let bestDist = Infinity;
  for (const p of model.patches) {
    const dist = Math.hypot(sx - p.cx, sy - p.cy);
    if (dist <= p.r && dist < bestDist) {
      best = p;
      bestDist = dist;
    }
  }
  if (best) {
    return bilinear(best.data, best.nx, best.ny, best.x0, best.x1, best.y0, best.y1, sx, sy);
  }
  const c = model.coarse;
  return bilinear(c.data, c.nx, c.ny, 0, DOMAIN_M, 0, DOMAIN_M, sx, sy);
}

function depthS(sx, sy) {
  return MISSION_CONFIG.TRUE_OCEAN_DEPTH_KM * 1000 - elevationS(sx, sy);
}

/** Seafloor depth (m) at website coords (x, y). Requires loadSeafloor() to have resolved. */
export function depthAt(x, y) {
  return depthS(x + DOMAIN_OFFSET_M, y + DOMAIN_OFFSET_M);
}

/**
 * Which hazard, if any, the point (x, y, z) is in. Chimneys are checked first
 * (they are the more specific hazard). Returns null when the point is clear.
 * The result shape matches what hazards.js expects from a collision.
 */
export function hazardAt(x, y, z) {
  const sx = x + DOMAIN_OFFSET_M;
  const sy = y + DOMAIN_OFFSET_M;
  const radius = MISSION_CONFIG.CHIMNEY_RADIUS_M;

  if (MISSION_CONFIG.ENABLE_VENT_COLLISIONS) {
    for (const v of model.vents) {
      const horiz = Math.hypot(sx - v.x, sy - v.y);
      if (horiz > radius) continue;
      const chimneyTop = depthS(v.x, v.y) - v.heightM; // shallower -> smaller z
      if (z >= chimneyTop) {
        return {
          type: "vent",
          hazardId: `vent-${v.ventId}`,
          label: `Hydrothermal Vent ${v.ventId}`
        };
      }
    }
  }

  if (MISSION_CONFIG.ENABLE_FLOOR_COLLISIONS && z >= depthS(sx, sy)) {
    return { type: "floor", hazardId: "ocean-floor", label: "Ocean floor" };
  }

  return null;
}
